make gpsd more robust

diff --git a/rootfs/etc/s6-overlay/scripts/gpsd b/rootfs/etc/s6-overlay/scripts/gpsd
--- a/rootfs/etc/s6-overlay/scripts/gpsd
+++ b/rootfs/etc/s6-overlay/scripts/gpsd
@@ -46,12 +46,17 @@ fi
 GPSD_ARGS+=("${GPSD_DEVICES}")
 echo "${GPSD_DEVICES}" > /run/gpsd/current_device
 
-"${s6wrap[@]}" echo "[INFO] Starting: $GPSD_BIN ${GPSD_ARGS[@]}"
-#shellcheck disable=SC2048,SC2086
-"${s6wrap[@]}" $GPSD_BIN ${GPSD_ARGS[*]} \
-    | grep -vi "Cannot assign requested address" \
-    | grep -vi "unable to connect to the DBUS system bus" \
-    || true
+if [[ -e "${GPSD_DEVICES}" ]]; then 
+    "${s6wrap[@]}" echo "[INFO] Starting: $GPSD_BIN ${GPSD_ARGS[@]}"
+    #shellcheck disable=SC2048,SC2086
+    "${s6wrap[@]}" $GPSD_BIN ${GPSD_ARGS[*]} \
+        | grep -vi "Cannot assign requested address" \
+        | grep -vi "unable to connect to the DBUS system bus" \
+        || true
 
-"${s6wrap[@]}" echo "[WARNING] Exited, restarting in 10 secs"
+    "${s6wrap[@]}" echo "[WARNING] Exited, restarting in 10 secs"
+else
+    "${s6wrap[@]}" echo "[WARNING] GPS device not found at ${GPSD_DEVICES}. Restarting in 10 secs"
+    rm -f /run/gpsd/current_device
+fi
 sleep 10
